[package]
name = "sqlite"
version = "0.1.0"
authors = ["Neeraj Jaiswal <neerajj85@gmail.com>"]
edition = "2018"

[dependencies]
rustyline="5.0.3"
scan_fmt="0.2.4"
bincode="1.2.0"
serde="1.0.101"
serde_derive="1.0.101"
